# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': '关卡记录表', 'verbose_name_plural': '关卡记录表'},
        ),
    ]
