# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-03-31 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '成语数据表',
                'verbose_name_plural': '成语数据表',
            },
        ),
    ]
