# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chengyu', '0002_auto_20190523_1335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordmodel1',
            options={'verbose_name': '关卡一', 'verbose_name_plural': '关卡一'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel10',
            options={'verbose_name': '关卡十', 'verbose_name_plural': '关卡十'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel2',
            options={'verbose_name': '关卡二', 'verbose_name_plural': '关卡二'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel3',
            options={'verbose_name': '关卡三', 'verbose_name_plural': '关卡三'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel4',
            options={'verbose_name': '关卡四', 'verbose_name_plural': '关卡四'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel5',
            options={'verbose_name': '关卡五', 'verbose_name_plural': '关卡五'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel6',
            options={'verbose_name': '关卡六', 'verbose_name_plural': '关卡六'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel7',
            options={'verbose_name': '关卡七', 'verbose_name_plural': '关卡七'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel8',
            options={'verbose_name': '关卡八', 'verbose_name_plural': '关卡八'},
        ),
        migrations.AlterModelOptions(
            name='wordmodel9',
            options={'verbose_name': '关卡九', 'verbose_name_plural': '关卡九'},
        ),
    ]
