# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chengyu', '0003_auto_20190524_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordModel11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十一',
                'verbose_name_plural': '关卡十一',
            },
        ),
        migrations.CreateModel(
            name='WordModel12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十二',
                'verbose_name_plural': '关卡十二',
            },
        ),
        migrations.CreateModel(
            name='WordModel13',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十三',
                'verbose_name_plural': '关卡十三',
            },
        ),
        migrations.CreateModel(
            name='WordModel14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十四',
                'verbose_name_plural': '关卡十四',
            },
        ),
        migrations.CreateModel(
            name='WordModel15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十五',
                'verbose_name_plural': '关卡十五',
            },
        ),
        migrations.CreateModel(
            name='WordModel16',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十六',
                'verbose_name_plural': '关卡十六',
            },
        ),
        migrations.CreateModel(
            name='WordModel17',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十七',
                'verbose_name_plural': '关卡十七',
            },
        ),
        migrations.CreateModel(
            name='WordModel18',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十八',
                'verbose_name_plural': '关卡十八',
            },
        ),
        migrations.CreateModel(
            name='WordModel19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡十九',
                'verbose_name_plural': '关卡十九',
            },
        ),
        migrations.CreateModel(
            name='WordModel20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('W_ans', models.CharField(max_length=200, verbose_name='答案')),
                ('W_init', models.CharField(max_length=200, verbose_name='初始位置')),
                ('W_finish', models.CharField(max_length=200, verbose_name='最终位置')),
            ],
            options={
                'verbose_name': '关卡二十',
                'verbose_name_plural': '关卡二十',
            },
        ),
    ]
